### PR TITLE
Use seperated prop-types package in examples

### PR DESCRIPTION
**Pull request by damusnet**
See #25 and #32

### CODE REVIEW

**Comment by jamsea** [comment]
@damusnet Can you add prop-types to package.json so Travis doesn't fail? Other than that it's good to merge in. Thanks again

**Comment by damusnet** [comment]
Oh right! I was wondering why one of the build was failing and not the other two.
I can definitely add it, however if you merge #32 first, it will already be there.
Not exactly sure how/if GitHub automatically rebases MR against the latest master.
In any case I think it's better if you merge #32 first, and then I can rebase to trigger a new Travis build if needed.

**Comment by imbhargav5** [comment]
Guys, do you need help? I need this fix haha.

**Comment by potench** [comment]
Build is failing, maybe bump the `prop-types` package version to latest and get that build passing

**Comment by potench** [comment]
@damusnet can you merge this into #34?

**Comment by potench** [comment]
Nevermind, just merged #32, so `rebase` #34 and this should pass.

**Comment by damusnet** [comment]
Thank you @potench :)

**Pull request merged**
