### PR TITLE
Use seperated prop-types package instead off access PropTypes via the…

### PR DESCRIPTION
**Pull request by nhducit**
… main React package

### CODE REVIEW

**Comment by jamsea** [comment]
Looks great @nhducit, thanks for the PR! Can you make the change for the code in the `example` folder too?

**Comment by nhducit** [comment]
@jamsea sure, I will update example folder by the end of today

**Comment by damusnet** [comment]
Hi @jamsea, any update on this PR? I have submitted #34 for the examples.
Thank you

**Comment by nhducit** [comment]
hi @damusnet and @jamsea, I'm sorry. I forgot this PR

**Comment by chielkunkels** [comment]
Any chance this will be merged soon? Is there work left to be done? Happy to pitch in.

**Pull request merged**
